# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('first', models.CharField(max_length=50, null=True)),
                ('last', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('bodyw', models.CharField(default='', max_length=50)),
                ('weightclass', models.CharField(max_length=50, null=True)),
                ('sq1', models.IntegerField(null=True)),
                ('sq2', models.IntegerField(null=True)),
                ('sq3', models.IntegerField(null=True)),
                ('bp1', models.IntegerField(null=True)),
                ('bp2', models.IntegerField(null=True)),
                ('bp3', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50, null=True)),
                ('last', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('weightclass', models.CharField(max_length=50, null=True)),
                ('agecategory', models.CharField(max_length=50, null=True)),
                ('affiliatedivision', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
