# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0002_auto_20170123_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestcycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50, null=True)),
                ('last', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
