# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0006_auto_20170202_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payplan',
            field=models.IntegerField(choices=[(12, '12'), (14, '14')], null=True),
        ),
    ]
