# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0007_auto_20170210_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='be1rm',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='de1rm',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='se1rm',
        ),
        migrations.AlterField(
            model_name='payments',
            name='last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lfit.PersonalInfo'),
        ),
    ]
