# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0008_auto_20170210_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='last',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='first',
        ),
    ]
