# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0009_auto_20170210_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='link',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='compresults',
            name='first',
        ),
        migrations.RemoveField(
            model_name='compresults',
            name='last',
        ),
        migrations.RemoveField(
            model_name='cyclecreate',
            name='first',
        ),
        migrations.RemoveField(
            model_name='cyclecreate',
            name='last',
        ),
        migrations.AddField(
            model_name='compresults',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lfit.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='cyclecreate',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lfit.PersonalInfo'),
        ),
    ]
