# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0015_auto_20170215_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
