# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0016_personalinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='last_login',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
