# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lfit', '0018_auto_20170217_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclecreate',
            name='trainingtype',
            field=models.CharField(choices=[('tra', 'TRAINING'), ('off', 'OFFSEASON'), ('pea', 'PEAKING')], max_length=50, null=True),
        ),
    ]
